language: minimal

dist: bionic

services:
  - docker

env:
  - IMAGE=alpine IMAGE_TAG=latest
  - IMAGE=archlinux IMAGE_TAG=latest
  - IMAGE=ubuntu IMAGE_TAG=latest
  - IMAGE=ubuntu IMAGE_TAG=rolling
  - IMAGE=ubuntu IMAGE_TAG=devel
  - IMAGE=fedora IMAGE_TAG=latest
  - IMAGE=fedora IMAGE_TAG=rawhide

before_install:
  - docker run -d --rm --cap-add SYS_PTRACE --name builder -e LC_ALL="en_US.UTF-8" -e LANG="en_US.UTF-8" -v $(pwd):/travis -w /travis $IMAGE:$IMAGE_TAG tail -f /dev/null
  - docker ps
  - docker exec -t builder sh .travis/preinstall.sh

install:
  - docker exec -t builder bash .travis/install-$IMAGE.sh
  - docker exec -t builder bash .travis/install-post.sh

script:
  - docker exec -t builder bash .travis/build.sh
  - docker kill builder

# vim: set ts=2 sts=2 sw=2 et:
