language: cpp

sudo: required

services:
  - docker

compiler:
  - gcc
  - clang

env:
  - IMAGE=ubuntu IMAGE_TAG=bionic
  - IMAGE=ubuntu IMAGE_TAG=cosmic
  - IMAGE=ubuntu IMAGE_TAG=disco
  - IMAGE=fedora IMAGE_TAG=latest
  - IMAGE=fedora IMAGE_TAG=rawhide

before_install:
  - export CONTAINER=${IMAGE}-${IMAGE_TAG}
  - docker run -d --name $CONTAINER -e LC_ALL="en_US.UTF-8" -e LANG="en_US.UTF-8" -v $(pwd):/travis -w /travis $IMAGE:$IMAGE_TAG tail -f /dev/null
  - docker ps

install:
  - docker exec -e CC=$CC -e CXX=$CXX -t $CONTAINER bash .travis/install-$IMAGE.sh
  - docker exec -e CC=$CC -e CXX=$CXX -t $CONTAINER bash .travis/install-post.sh

script:
  - docker exec -e CC=$CC -e CXX=$CXX -t $CONTAINER bash .travis/script.sh

# vim: set ts=2 sts=2 sw=2 et:
