language: cpp

sudo: required

services:
  - docker

compiler:
  - gcc
  - clang

env:
  - CONTAINER=bionic
  - CONTAINER=cosmic
  - CONTAINER=disco

before_install:
  - docker run -d --name $CONTAINER -e LC_ALL="en_US.UTF-8" -e LANG="en_US.UTF-8" -v $(pwd):/travis -w /travis ubuntu:$CONTAINER tail -f /dev/null
  - docker ps

install:
  - docker exec -e CC=$CC -e CXX=$CXX -t $CONTAINER bash .travis/install.sh

script:
  - docker exec -e CC=$CC -e CXX=$CXX -t $CONTAINER bash .travis/script.sh

# vim: set ts=2 sts=2 sw=2 et:
